# My First Pytorch notebook

In [1]:
import torch
import numpy as np 

In [2]:
t = torch.Tensor()

In [3]:
type(t)

torch.Tensor

In [4]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [5]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [6]:
torch.tensor(data)

tensor([1, 2, 3])

In [7]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [8]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [9]:
torch.from_numpy(data)

tensor([1, 2, 3])

# Creation Options Without Data


In [10]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [11]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [12]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [13]:
torch.rand(2,2)

tensor([[0.9220, 0.8335],
        [0.5732, 0.7581]])

# Creating PyTorch tensors - best options

In [14]:
t1 = torch.tensor(data) # factory function
t2 = torch.Tensor(data) #constructor function
t3 = torch.as_tensor(data)# factory function
t4 = torch.from_numpy(data)# factory function

In [15]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.int64
torch.float32
torch.int64
torch.int64


In [16]:
torch.get_default_dtype()

torch.float32

In [17]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [18]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3])

In [19]:
data[0] = 0
data[1] = 0
data[2] = 0

In [20]:
print(t1)
print(t2)

tensor([1, 2, 3])
tensor([1., 2., 3.])


In [21]:
print(t3)
print(t4)

tensor([0, 0, 0])
tensor([0, 0, 0])


In [22]:
lst = [1,2,3]
torch.as_tensor(lst) # can convert lists also to tensor

tensor([1, 2, 3])

# Reshaping Explained

In [23]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [24]:
t.size()

torch.Size([3, 4])

In [25]:
t.shape

torch.Size([3, 4])

In [26]:
len(t.shape)

2

In [27]:
torch.tensor(t.shape).prod() 

tensor(12)

In [28]:
t.numel() # no. of elements

12

In [29]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [30]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [31]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [32]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [33]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [34]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [35]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])